### ISSUE TITLE
Enhancement - Dockerfile + gist links (herding cats)

### ISSUE THREAD

**Issue by johndpope** [Awesome-Server-Side-Swift/TheList#17]
With all of these projects - getting a suitable environment up and running in short time is helpful for newbies wanting to test drive swift development and these projects. 
I imagine swift3 could find it's way into microservices and docker is great architecture for this to prosper. 

With so many likes for this list - it would be powerful to have developers pool resources together to save time.  

Being able to quickly fire up any of these with projects with a default docker would be 'awesome'

Pull the Docker Image From Docker Hub:
**docker pull swiftdocker/swift**
Create a Container from the Image and Attach It:
**docker run --privileged -i -t --name swiftfun swiftdocker/swift:latest /bin/bash**

In two lines of code - you can have a linux / swift3 environment up and running.

Now to plugin projects... this is a bit harder. but it need not be.
I built this Dockerfile the other day which appends a bash shell script to do a git checkout and build.

https://github.com/johndpope/DockerParseyMcParsefaceAPI/blob/master/docker/dsparseyapi/Dockerfile

My request is to consider requesting people to help pool gist scripts to run each 'hello world' sample with above docker container.

Then for each of the server side projects - getting these to run with minimal effort would benefit to people . 

I will draft something and if suitable submit PR.

I'm imagining a list like this with icons to fire up docker -> 
![screen shot 2016-10-20 at 15 20 45](https://cloud.githubusercontent.com/assets/289994/19574502/b02438f0-96d8-11e6-849a-fc0f1e02cade.png)
https://github.com/open-guides/og-aws

UPDATE 
Need to consider instructions to use oauth token with docker. 
https://devops.profitbricks.com/tutorials/configure-a-docker-container-to-automatically-pull-from-github-using-oauth/

It's possible to create a restricted cloning token.
![gists_token](https://cloud.githubusercontent.com/assets/289994/19574921/4af3b45e-96da-11e6-97e1-37aacb4e0d2c.png)

from here one can clone respective repos.
eg.
**git clone  https://tokenhere@github.com:Alamofire/Alamofire.git**

**Comment by iamjono** [comment]
I agree - that would be ideal. 
I'm sure each of the projects has such a thing, so I'll reach out to each team soon!

Thanks :)

**Comment by johndpope** [comment]
fyi - I created this subclassed the base swift3 image to add ssh https://gist.github.com/johndpope/01a74ffb93921df48e334097117be1b3
